# Generated by Django 4.1.13 on 2024-02-07 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('college_name', models.CharField(max_length=225)),
                ('designation', models.CharField(max_length=225)),
                ('display_image', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=2)),
                ('password', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_role', models.CharField(max_length=2)),
                ('mentor_id_card', models.ImageField(blank=True, null=True, upload_to='uploads/mentor_id')),
                ('report_count', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('community_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('community_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=200)),
                ('report_count', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_community', to='api.community')),
                ('question_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('conversation_id', models.SmallIntegerField()),
                ('content', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_community', to='api.community')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_status', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coversation_community', to='api.community')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_from', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_id', models.IntegerField()),
                ('answer_content', models.CharField(max_length=255)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_count', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('answer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_given', to=settings.AUTH_USER_MODEL)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_community', to='api.community')),
                ('liked_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='community_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_community_selected', to='api.community'),
        ),
    ]
