# Generated by Django 4.1.13 on 2024-02-07 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='user_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='community_id',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='user_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='community_id',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='from_user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='to_user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='messages',
            name='community_id',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='community_id',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='community_id',
            field=models.SmallIntegerField(),
        ),
    ]
