# Generated by Django 4.1.13 on 2024-02-21 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='answer_reported_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='question_reported_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
